### ISSUE TITLE
Link to the website

### ISSUE THREAD

**Issue by stared** [gnsmrky/pytorch-fast-neural-style-onnxjs#5]
I had to deduce that it is accessible here:

* https://gnsmrky.github.io/pytorch-fast-neural-style-onnxjs/

It would be nice if that link were in the repo tagline + README.md.

**Comment by gnsmrky** [comment]
@stared Good catch!  I was working on making the PyTorch part of the project in past few weeks.  Just added few links to the README.md.  Thanks for bringing it up!
